q1 = input("What is your favorite animal?\n>")
q2 = input("Do they fly, walk, or swim?\n>")
q3 = input("What sound does the animal make?\n>")
q4 = input("Where do they live?\n>")
q5 = input("Why do you like them?\n>")
q6 = input("Why is this your favorite animal?\n>")
q7 = input("Do they have scales, fur, feathers, or do they feel slimy?\n>")
q8 = input("what color are they?\n>")
q9 = input("What is a fun fact about them?\n>")
q10 = input("Is it a pet or a wild animal?\n>")
q11 = input("How big is the animal?\n>")
q12 = input("How big is the animal?\n>")

summary = print("So, your favorite animal is" + q1 + " " + q2  + "!")
